server:
  port: 8081
dubbo:
  application:
    name: order-service-consumer #服务名称
    qos-port: 33333 # telnet端口与dubbo协议的端口是不同的端口，默认为22222
  registry:
    address:  127.0.0.1:2181 #地址
    protocol: zookeeper #注册中心
    check: false #启动时是否检查注册中心有
  # monitor: #监控中心
    # address: registry
  consumer:
    check: false #当前所有的服务启动时都不检查(如果是true的话启动的时候会检查每一个是否在zk中存在，不存在则报错)
    timeout: 1000 #客户端调用服务端的超时配置(单位/毫秒)
    retries: 3 #重试次数(在调用失败的情况下,重新调用该服务,不含第一次重试3次)
    # version: *  #匹配任意的版本进行调用
